In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import io

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving accidentes.csv to accidentes.csv


In [141]:
accidentes = pd.read_csv(io.BytesIO(uploaded['accidentes.csv']),encoding="latin-1")
accidentes

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (2,12) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Unnamed: 0   AÑO CBML  ...     HORAS          X         Y
0                1  2014  NaN  ...  20:30:00 -75.703776  6.221415
1                2  2014  NaN  ...  19:50:00 -75.703776  6.221415
2                3  2014  NaN  ...  13:00:00 -75.703776  6.221415
3                4  2014  NaN  ...  18:00:00 -75.703776  6.221415
4                5  2014  NaN  ...  00:45:00 -75.703776  6.221415
...            ...   ...  ...  ...       ...        ...       ...
270325      270326  2020  917  ...  15:30:00 -75.528300  6.228257
270326      270327  2020  917  ...  18:50:00 -75.528300  6.228257
270327      270328  2020  917  ...  22:50:00 -75.530705  6.228336
270328      270329  2020  917  ...  13:00:00 -75.528326  6.228219
270329      270330  2020  917  ...  19:15:00 -75.528300  6.228257

[270330 rows x 23 columns]

In [142]:
accidentesBarrio = accidentes[~accidentes["BARRIO"].isnull()]
accidentesBarrio = accidentesBarrio.drop(["Unnamed: 0","CBML","DIRECCION.ENCASILLADA","DISEÑO","EXPEDIENTE","LOCATION"],axis=1)
accidentesBarrio = accidentesBarrio.dropna()
accidentesBarrio

AÑO CLASE_ACCIDENTE         DIRECCION  ...     HORAS          X         Y
1659    2014       Atropello  CL 102 B CR 32 C  ...  18:30:00 -75.542488  6.292502
1660    2014       Atropello    CL 103 CR 32 A  ...  14:35:00 -75.542718  6.293151
1661    2014       Atropello      CL 104 CR 33  ...  11:50:00 -75.542234  6.293109
1662    2014       Atropello      CL 106 CR 32  ...  03:10:00 -75.542174  6.293409
1663    2014       Atropello    CR 30 CL 110 A  ...  23:30:00 -75.542009  6.298411
...      ...             ...               ...  ...       ...        ...       ...
270325  2020       Atropello      CL 46 CR 2 B  ...  15:30:00 -75.528300  6.228257
270326  2020          Choque        CL 46 CR 2  ...  18:50:00 -75.528300  6.228257
270327  2020          Choque   CL 46 D CR 2 AE  ...  22:50:00 -75.530705  6.228336
270328  2020            Otro        CR 1 CL 46  ...  13:00:00 -75.528326  6.228219
270329  2020     Volcamiento   CL 46 B CR 2 AG  ...  19:15:00 -75.528300  6.228257

[250069 rows x 17 columns]

In [143]:
X = accidentesBarrio[["AÑO","CLASE_ACCIDENTE","COMUNA","HORA","X","Y"]]
y = accidentesBarrio["BARRIO"]
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0,train_size=0.7)
X_train

AÑO     CLASE_ACCIDENTE  ...          X         Y
154046  2017         Volcamiento  ... -75.577420  6.190472
236782  2019  Caída del ocupante  ... -75.592106  6.250952
216580  2019              Choque  ... -75.573780  6.275443
122194  2017              Choque  ... -75.563347  6.264127
187863  2018              Choque  ... -75.569008  6.238675
...      ...                 ...  ...        ...       ...
192529  2018              Choque  ... -75.590246  6.249371
130302  2017           Atropello  ... -75.572534  6.280659
189250  2018              Choque  ... -75.585941  6.248873
48738   2015           Atropello  ... -75.561813  6.252991
217452  2019              Choque  ... -75.582438  6.285789

[175048 rows x 6 columns]

In [144]:
y_train = y_train.astype("category")
y_train

154046    Santa María de los Ángeles
236782                 Florida Nueva
216580                   El Progreso
122194                       Sevilla
187863                     San Diego
                     ...            
192529                 Florida Nueva
130302                       Córdoba
189250                      Naranjal
48738                    Villa Nueva
217452                       Kennedy
Name: BARRIO, Length: 175048, dtype: category
Categories (320, object): ['AUC1', 'Aguas Frias', 'Aguas Frías', 'Aguas frías', ...,
                           'Área de expansión Altos de Calasanz', 'Área de expansión Belén Rincón',
                           'Área de expansión Pajarito', 'Área de expansión San Antonio de Prado']

In [145]:
from sklearn import preprocessing
def convert(Data):
  for column in Data.columns:
    number = preprocessing.LabelEncoder()
    if column != "NRO_RADICADO":
      Data[column] = number.fit_transform(Data[column])
  return Data

In [146]:
X_train = convert(X_train)
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()
X_train = scale.fit_transform(X_train) 
X_train

array([[ 0.02335851,  2.68224327, -0.01231573, -0.8693625 , -0.15470687,
        -1.58395417],
       [ 1.16041665, -0.94715249,  0.69025657,  0.74950826, -0.94726313,
        -0.00339391],
       [ 1.16041665, -0.03980355, -1.24181723, -0.32973891,  0.08987596,
         0.92133415],
       ...,
       [ 0.59188758, -0.03980355,  0.69025657,  1.28604829, -0.66905017,
        -0.12190094],
       [-1.11369963, -1.85450143,  0.51461349,  0.56449446,  0.88387095,
         0.0816761 ],
       [ 1.16041665, -0.03980355, -0.1879588 , -0.7768556 , -0.45432083,
         1.35679305]])

In [147]:
X_test = convert(X_test)
scale = StandardScaler()
X_test = scale.fit_transform(X_test) 
X_test

array([[-0.54404731, -0.04712006,  1.0374757 ,  0.8622043 ,  1.93348316,
         1.55820843],
       [ 1.15773474, -0.04712006, -1.5884568 ,  1.50991822, -1.40121483,
        -0.77349913],
       [-1.111308  , -0.04712006, -1.23833247, -1.05207894, -0.28651185,
         0.78766286],
       ...,
       [-1.111308  , -0.04712006,  0.5122892 ,  0.78204168, -0.04554184,
        -0.21587894],
       [ 1.15773474, -0.04712006, -1.23833247,  0.76600916,  1.13875268,
         1.92799177],
       [ 0.02321337, -0.04712006,  0.5122892 ,  1.05459457,  0.36854023,
        -0.95064607]])

In [148]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors = 5)

In [149]:
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [150]:
knn.score(X_train, y_train)

0.7659898999131667

In [151]:
knn.score(X_test, y_test)

0.6192132869463217

In [152]:
accidentesBarrioNull = accidentes[accidentes["BARRIO"].isnull()]
accidentesBarrioNull = accidentesBarrioNull.drop(["Unnamed: 0","CBML","DIRECCION.ENCASILLADA","DISEÑO","EXPEDIENTE","LOCATION"],axis=1)
accidentesBarrioNull = accidentesBarrioNull[["AÑO","CLASE_ACCIDENTE","COMUNA","HORA","X","Y"]]
accidentesBarrioNull = convert(accidentesBarrioNull)
scale = StandardScaler()
accidentesBarrioNull = scale.fit_transform(accidentesBarrioNull) 
accidentesBarrioNull


array([[-1.67480691, -1.75791011,  0.44055184,  0.44676442, -0.04065764,
        -0.15122634],
       [-1.67480691, -1.75791011,  0.44055184,  0.33661314, -0.04065764,
        -0.15122634],
       [-1.67480691, -1.75791011,  0.44055184, -0.92773204, -0.04065764,
        -0.15122634],
       ...,
       [ 1.78052307, -0.97349783, -7.03386724, -0.40092155, -0.1735041 ,
         0.04549528],
       [ 1.78052307, -0.18908554, -6.49998017,  1.75421227, -0.1735041 ,
         0.04549528],
       [ 1.78052307, -0.18908554, -4.89831894,  1.17472073, -0.1735041 ,
         0.04549528]])

In [136]:
accidentesBarrioNull

array([[-2.998165  , -1.0776197 , -5.04997117, -0.68465778,  0.37236376,
        -3.63000847],
       [-2.998165  , -0.00933616, -1.51927693, -1.72403345,  0.20998409,
        -2.73654558],
       [-2.998165  , -0.00933616, -5.04997117, -1.88531588,  0.37236376,
        -3.63000847],
       ...,
       [ 8.52748635, -1.0776197 , -5.63842021, -0.62193683, -0.27715492,
        -0.05615692],
       [ 8.52748635, -0.00933616, -5.04997117,  1.63601721, -0.27715492,
        -0.05615692],
       [ 8.52748635, -0.00933616, -3.28462405,  1.0984091 , -0.27715492,
        -0.05615692]])

In [153]:
barriosPred = knn.predict(accidentesBarrioNull)

In [154]:
barriosPred.shape


(20232,)

In [156]:
barriosPred

array(['Corazón de Jesús', 'Corazón de Jesús', 'Guayaquil', ...,
       'Universidad de Antioquia', 'Universidad de Antioquia',
       'Universidad de Antioquia'], dtype=object)

In [155]:
accidentes.loc[accidentes["BARRIO"].isnull(),"BARRIO"] = barriosPred

In [158]:
accidentes[accidentes["BARRIO"].isnull()]

Empty DataFrame
Columns: [Unnamed: 0, AÑO, CBML, CLASE_ACCIDENTE, DIRECCION, DIRECCION.ENCASILLADA, DISEÑO, EXPEDIENTE, FECHA_ACCIDENTE, FECHA_ACCIDENTES, GRAVEDAD, MES, NRO_RADICADO, NUMCOMUNA, BARRIO, COMUNA, LOCATION, FUENTE, FECHA, HORA, HORAS, X, Y]
Index: []

In [157]:
accidentes["BARRIO"] = accidentes.BARRIO.astype(str)
accidentesNuevos = accidentes.iloc[:,1:]
accidentesNuevos

AÑO CBML CLASE_ACCIDENTE  ...     HORAS          X         Y
0       2014  NaN       Atropello  ...  20:30:00 -75.703776  6.221415
1       2014  NaN       Atropello  ...  19:50:00 -75.703776  6.221415
2       2014  NaN       Atropello  ...  13:00:00 -75.703776  6.221415
3       2014  NaN       Atropello  ...  18:00:00 -75.703776  6.221415
4       2014  NaN       Atropello  ...  00:45:00 -75.703776  6.221415
...      ...  ...             ...  ...       ...        ...       ...
270325  2020  917       Atropello  ...  15:30:00 -75.528300  6.228257
270326  2020  917          Choque  ...  18:50:00 -75.528300  6.228257
270327  2020  917          Choque  ...  22:50:00 -75.530705  6.228336
270328  2020  917            Otro  ...  13:00:00 -75.528326  6.228219
270329  2020  917     Volcamiento  ...  19:15:00 -75.528300  6.228257

[270330 rows x 22 columns]

In [161]:
accidentesNuevos.to_csv('/content/drive/My Drive/Julian/accidentesConBarrio2.csv',index=False)

In [160]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive
