In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import io

In [2]:
from google.colab import files
uploaded = files.upload()

Saving accidentesMDE2.csv to accidentesMDE2.csv


In [4]:
accidentes = pd.read_csv(io.BytesIO(uploaded['accidentesMDE2.csv']),encoding="latin-1")
accidentes

Unnamed: 0      FECHA_ACCIDENTE   AÑO  ... FLORES FUTBOL QUINCENA
0                1  2014-07-19 15:30:00  2014  ...      0      0        0
1                2  2014-10-25 14:50:00  2014  ...      0      0        0
2                3  2014-11-20 08:00:00  2014  ...      0      0        1
3                4  2014-12-02 13:00:00  2014  ...      0      0        0
4                5  2014-12-18 19:45:00  2014  ...      0      0        0
...            ...                  ...   ...  ...    ...    ...      ...
270325      270326  2020-03-03 10:30:00  2020  ...      0      0        0
270326      270327  2020-02-27 13:50:00  2020  ...      0      0        0
270327      270328  2020-01-31 17:50:00  2020  ...      0      0        0
270328      270329  2020-02-05 08:00:00  2020  ...      0      0        1
270329      270330  2020-08-27 14:15:00  2020  ...      0      0        0

[270330 rows x 27 columns]

In [6]:
accidentesBarrio = accidentes[~accidentes["BARRIO"].isnull()]
#accidentesBarrio = accidentesBarrio.drop(["Unnamed: 0","CBML","DIRECCION.ENCASILLADA","DISEÑO","EXPEDIENTE","LOCATION"],axis=1)
accidentesBarrio = accidentesBarrio.dropna()
accidentesBarrio

Unnamed: 0      FECHA_ACCIDENTE   AÑO  ... FLORES FUTBOL QUINCENA
1659          1660  2014-07-06 13:30:00  2014  ...      0      0        0
1660          1661  2014-10-03 09:35:00  2014  ...      0      0        0
1661          1662  2014-07-11 06:50:00  2014  ...      0      0        0
1662          1663  2014-11-23 22:10:00  2014  ...      0      0        0
1663          1664  2014-10-18 18:30:00  2014  ...      0      0        0
...            ...                  ...   ...  ...    ...    ...      ...
270325      270326  2020-03-03 10:30:00  2020  ...      0      0        0
270326      270327  2020-02-27 13:50:00  2020  ...      0      0        0
270327      270328  2020-01-31 17:50:00  2020  ...      0      0        0
270328      270329  2020-02-05 08:00:00  2020  ...      0      0        1
270329      270330  2020-08-27 14:15:00  2020  ...      0      0        0

[249288 rows x 27 columns]

In [8]:
X = accidentesBarrio[["AÑO","CLASE_ACCIDENTE","COMUNA","HORA","LONGITUD","LATITUD"]]
y = accidentesBarrio["BARRIO"]
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0,train_size=0.7)
X_train

AÑO     CLASE_ACCIDENTE  ...   LONGITUD   LATITUD
146891  2017  Caída del ocupante  ... -75.596093  6.266268
154869  2017              Choque  ... -75.578243  6.225838
54630   2015           Atropello  ... -75.596459  6.263333
144319  2017              Choque  ... -75.580520  6.248002
144630  2017              Choque  ... -75.586158  6.247391
...      ...                 ...  ...        ...       ...
193208  2018           Atropello  ... -75.600411  6.255498
130744  2017                Otro  ... -75.587289  6.282352
189916  2018              Choque  ... -75.583118  6.240029
48931   2015              Choque  ... -75.561115  6.252519
218187  2019              Choque  ... -75.586979  6.265979

[174501 rows x 6 columns]

In [9]:
y_train = y_train.astype("category")
y_train

146891           Los Colores
154869              Santa Fe
54630             El Estadio
144319              Naranjal
144630           San Joaquín
                 ...        
193208           La Floresta
130744           El Diamante
189916    Los Conquistadores
48931            Villa Nueva
218187            San Germán
Name: BARRIO, Length: 174501, dtype: category
Categories (312, object): ['Aguas Frías', 'Aldea Pablo VI', 'Alejandro Echavarría', 'Alejandría',
                           ..., 'Área de expansión Altos de Calasanz',
                           'Área de expansión Belén Rincón', 'Área de expansión Pajarito',
                           'Área de expansión San Antonio de Prado']

In [10]:
from sklearn import preprocessing
def convert(Data):
  for column in Data.columns:
    number = preprocessing.LabelEncoder()
    if column != "NRO_RADICADO":
      Data[column] = number.fit_transform(Data[column])
  return Data

In [11]:
X_train = convert(X_train)
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()
X_train = scale.fit_transform(X_train) 
X_train

array([[ 0.02197544, -0.95417821,  0.69330126,  0.38215192, -1.15658999,
         0.63973842],
       [ 0.02197544, -0.04470218,  0.16581357, -1.30806686, -0.18090792,
        -1.06531174],
       [-1.11373771, -1.86365424,  0.69330126,  1.12239372, -1.1762459 ,
         0.54217646],
       ...,
       [ 0.58983201, -0.04470218,  0.69330126,  1.4308278 , -0.49540253,
        -0.49886507],
       [-1.11373771, -0.04470218,  0.51747203, -1.77688667,  0.93292713,
         0.0956429 ],
       [ 1.15768858, -0.04470218,  1.22078896, -0.66343963, -0.7256575 ,
         0.63043903]])

In [12]:
X_test = convert(X_test)
scale = StandardScaler()
X_test = scale.fit_transform(X_test) 
X_test

array([[ 0.59161065, -0.04365588,  0.51024413, -0.38121178,  0.81160754,
        -0.34870408],
       [-0.54495474, -1.84945899, -0.01484982,  0.88883177,  0.00711222,
        -1.07684784],
       [-1.11323743,  1.76214723, -1.24006905,  1.04718326,  0.29320009,
         1.24799994],
       ...,
       [-1.11323743, -0.04365588,  0.51024413, -1.11803094,  0.02816301,
        -0.24535754],
       [ 0.59161065, -0.04365588,  0.16018149,  0.22957252, -0.69644075,
        -1.52438328],
       [ 0.59161065, -1.84945899,  1.2103694 , -0.187312  , -1.54937826,
         1.05074285]])

In [13]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors = 5)

In [14]:
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [15]:
knn.score(X_train, y_train)

0.7668265511372427

In [16]:
knn.score(X_test, y_test)

0.6153743297631942

In [17]:
accidentesBarrioNull = accidentes[accidentes["BARRIO"].isnull()]
#accidentesBarrioNull = accidentesBarrioNull.drop(["Unnamed: 0","CBML","DIRECCION.ENCASILLADA","DISEÑO","EXPEDIENTE","LOCATION"],axis=1)
accidentesBarrioNull = accidentesBarrioNull[["AÑO","CLASE_ACCIDENTE","COMUNA","HORA","LONGITUD","LATITUD"]]
accidentesBarrioNull = convert(accidentesBarrioNull)
scale = StandardScaler()
accidentesBarrioNull = scale.fit_transform(accidentesBarrioNull) 
accidentesBarrioNull


array([[-1.67480691, -1.75791011,  0.44055184,  0.44676442, -0.16659438,
         0.03651819],
       [-1.67480691, -1.75791011,  0.44055184,  0.33661314, -0.16659438,
         0.03651819],
       [-1.67480691, -1.75791011,  0.44055184, -0.92773204, -0.16659438,
         0.03651819],
       ...,
       [ 1.78052307, -0.97349783, -7.03386724, -0.40092155, -0.16659438,
         0.03651819],
       [ 1.78052307, -0.18908554, -6.49998017,  1.75421227, -0.16659438,
         0.03651819],
       [ 1.78052307, -0.18908554, -4.89831894,  1.17472073, -0.16659438,
         0.03651819]])

In [18]:
accidentesBarrioNull

array([[-1.67480691, -1.75791011,  0.44055184,  0.44676442, -0.16659438,
         0.03651819],
       [-1.67480691, -1.75791011,  0.44055184,  0.33661314, -0.16659438,
         0.03651819],
       [-1.67480691, -1.75791011,  0.44055184, -0.92773204, -0.16659438,
         0.03651819],
       ...,
       [ 1.78052307, -0.97349783, -7.03386724, -0.40092155, -0.16659438,
         0.03651819],
       [ 1.78052307, -0.18908554, -6.49998017,  1.75421227, -0.16659438,
         0.03651819],
       [ 1.78052307, -0.18908554, -4.89831894,  1.17472073, -0.16659438,
         0.03651819]])

In [19]:
barriosPred = knn.predict(accidentesBarrioNull)

In [20]:
barriosPred.shape


(20232,)

In [ ]:
barriosPred

array(['Corazón de Jesús', 'Corazón de Jesús', 'Guayaquil', ...,
       'Universidad de Antioquia', 'Universidad de Antioquia',
       'Universidad de Antioquia'], dtype=object)

In [21]:
accidentes.loc[accidentes["BARRIO"].isnull(),"BARRIO"] = barriosPred

In [22]:
accidentes[accidentes["BARRIO"].isnull()]

Empty DataFrame
Columns: [Unnamed: 0, FECHA_ACCIDENTE, AÑO, MES, FECHA, HORA, CLASE_ACCIDENTE, DISEÑO, GRAVEDAD_ACCIDENTE, BARRIO, COMUNA, X_MAGNA, Y_MAGNA, LONGITUD, LATITUD, COMUNASMOD, DIAX, MESX, AÑOX, SEMANAX, SEMANAXX, DIA_SEMANA, MES_SEMANA, FESTIVO, FLORES, FUTBOL, QUINCENA]
Index: []

In [23]:
accidentes["BARRIO"] = accidentes.BARRIO.astype(str)
accidentesNuevos = accidentes.iloc[:,1:]
accidentesNuevos

FECHA_ACCIDENTE   AÑO        MES  ... FLORES FUTBOL QUINCENA
0       2014-07-19 15:30:00  2014      Julio  ...      0      0        0
1       2014-10-25 14:50:00  2014    Octubre  ...      0      0        0
2       2014-11-20 08:00:00  2014  Noviembre  ...      0      0        1
3       2014-12-02 13:00:00  2014  Diciembre  ...      0      0        0
4       2014-12-18 19:45:00  2014  Diciembre  ...      0      0        0
...                     ...   ...        ...  ...    ...    ...      ...
270325  2020-03-03 10:30:00  2020      Marzo  ...      0      0        0
270326  2020-02-27 13:50:00  2020     Febero  ...      0      0        0
270327  2020-01-31 17:50:00  2020      Enero  ...      0      0        0
270328  2020-02-05 08:00:00  2020     Febero  ...      0      0        1
270329  2020-08-27 14:15:00  2020     Agosto  ...      0      0        0

[270330 rows x 26 columns]

In [26]:
accidentesNuevos.to_csv('/content/drive/My Drive/Julian/accidentesConBarrio2.csv',index=False)

In [25]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive
